#!/bin/sh

################################################################################
# Specify the filepath of the verilog library file of standard cell
################################################################################
VERILOG_LIB=/afs/ee.ust.hk/staff/ee/dept/public/elec516/eesm_5020_2017spring/eesm_5020/lib/NangateOpenCellLibrary_PDKv1_3_v2010_12/Front_End/Verilog/NangateOpenCellLibrary.v

SDF_LOCATION="../syn/results/processor_new.mapped.sdf"

vcs -full64 ../syn/results/processor_new.mapped.v ../tb/tb.v +v2k -debug_all -top tb \
  -timescale=1ns/1ps +neg_tchk +warn=noTFIPC -v $VERILOG_LIB +define+SDF_FILE=\"$SDF_LOCATION\"