###############################################################
#  Generated by:      Cadence Innovus 20.10-p004_1
#  OS:                Linux x86_64(Host ID EEX052)
#  Generated on:      Mon May 30 20:12:44 2022
#  Design:            processor
#  Command:           routeDesign -globalDetail
###############################################################
current_design processor
create_clock  -name clk -period 10.000000 -waveform {0.000000 5.000000}
